# Generated by Django 3.1.6 on 2021-03-10 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0005_paymentmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('type', 'name')},
        ),
    ]
