# Generated by Django 3.1.6 on 2021-03-10 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0007_auto_20210310_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('alpha_two_code', models.CharField(max_length=2)),
                ('alpha_three_code', models.CharField(max_length=3)),
            ],
        ),
    ]
