# Generated by Django 3.1.7 on 2021-04-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_coins_bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_coins_sold',
            field=models.IntegerField(default=0),
        ),
    ]
