# Generated by Django 3.1.6 on 2021-03-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='memo',
            field=models.CharField(default='tnbcrow-<function uuid4 at 0x037FF978>', editable=False, max_length=44, unique=True),
        ),
    ]
