# Generated by Django 3.1.6 on 2021-03-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210303_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reputation',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='memo',
            field=models.CharField(default='tnbcrow-<function uuid4 at 0x03DCB858>', editable=False, max_length=44, unique=True),
        ),
    ]
