# Generated by Django 3.1.6 on 2021-03-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210303_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='memo',
            field=models.CharField(default='tnbcrow-<function uuid4 at 0x03BBF8A0>', editable=False, max_length=44, unique=True),
        ),
    ]
