# Generated by Django 3.1.6 on 2021-03-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210306_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='memo',
            field=models.CharField(default='tnbcrow-<function uuid4 at 0x03C5F8A0>', editable=False, max_length=44, unique=True),
        ),
    ]
