# Generated by Django 3.1.6 on 2021-03-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210306_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='memo',
            field=models.CharField(default='tnbcrow-<function uuid4 at 0x0386F8E8>', editable=False, max_length=44, unique=True),
        ),
    ]
