# Generated by Django 3.1.6 on 2021-03-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210312_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='memo',
            field=models.CharField(default='tnbcrow-<function uuid4 at 0x03F2F978>', editable=False, max_length=44, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(max_length=64),
        ),
    ]
