# Generated by Django 3.1.6 on 2021-03-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210312_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='memo',
            field=models.CharField(default='tnbcrow-<function uuid4 at 0x0328F978>', editable=False, max_length=44, unique=True),
        ),
    ]
