# Generated by Django 3.1.6 on 2021-03-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210314_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='memo',
            field=models.CharField(default='tnbcrow-<function uuid4 at 0x03E8F978>', editable=False, max_length=44, unique=True),
        ),
    ]
