# Generated by Django 3.1.7 on 2021-03-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210314_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='memo',
            field=models.CharField(editable=False, max_length=44, unique=True),
        ),
    ]
