# Generated by Django 3.1.6 on 2021-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepost',
            name='trade_type',
            field=models.IntegerField(choices=[(0, 'Buy'), (1, 'Sell')], default=0),
            preserve_default=False,
        ),
    ]
