# Generated by Django 3.1.7 on 2021-04-12 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20210412_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 15, 0, 2, 953115, tzinfo=utc)),
        ),
    ]
