# Generated by Django 3.1.6 on 2021-03-10 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0001_initial'),
        ('trades', '0002_auto_20210310_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepost',
            name='transaction_detail',
            field=models.ForeignKey(default='eb12f7fc-5e8e-4b3b-9671-6691167903d3', on_delete=django.db.models.deletion.CASCADE, to='constants.transactiondetail'),
            preserve_default=False,
        ),
    ]
