# Generated by Django 3.1.6 on 2021-03-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_tradepost_trade_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradepost',
            name='margin',
            field=models.IntegerField(default=100),
        ),
    ]
