# Generated by Django 3.1.7 on 2021-04-13 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20210412_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 17, 37, 16, 236410, tzinfo=utc)),
        ),
    ]
