# Generated by Django 3.1.7 on 2021-04-21 03:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20210412_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradepost',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='tradepost',
            name='margin',
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 3, 49, 3, 3911, tzinfo=utc)),
        ),
    ]
