# Generated by Django 3.1.6 on 2021-03-06 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0003_auto_20210306_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradepost',
            old_name='final_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='tradepost',
            name='broadcast_trade',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.tradepost')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveTrade',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initiator_accepted', models.BooleanField(default=False)),
                ('owner_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.tradepost')),
            ],
        ),
    ]
