# Generated by Django 3.1.6 on 2021-03-10 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0007_auto_20210310_0950'),
        ('trades', '0004_auto_20210310_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepost',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constants.paymentmethod'),
            preserve_default=False,
        ),
    ]
