# Generated by Django 3.1.6 on 2021-03-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_auto_20210307_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradepost',
            old_name='max_transaction',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='tradepost',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='tradepost',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='tradepost',
            name='min_transaction',
        ),
        migrations.RemoveField(
            model_name='tradepost',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tradepost',
            name='trade_type',
        ),
        migrations.AddField(
            model_name='tradepost',
            name='owner_role',
            field=models.IntegerField(choices=[(0, 'Buyer'), (1, 'Seller')], default=0),
            preserve_default=False,
        ),
    ]
