# Generated by Django 3.1.7 on 2021-05-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_auto_20210421_1056'),
        ('trades', '0004_auto_20210413_1737'),
    ]

    operations = [
    ]
