# Generated by Django 3.1.6 on 2021-03-10 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0007_auto_20210310_0950'),
        ('trades', '0005_tradepost_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepost',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constants.exchange'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradepost',
            name='margin',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='tradepost',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
