# Generated by Django 3.1.7 on 2021-05-04 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_merge_20210504_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 16, 57, 5, 337235, tzinfo=utc)),
        ),
    ]
