# Generated by Django 3.1.6 on 2021-03-09 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0001_initial'),
        ('trades', '0006_auto_20210309_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exchange',
        ),
        migrations.AlterField(
            model_name='tradepost',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constants.paymentmethod'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
