# Generated by Django 3.1.6 on 2021-03-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_auto_20210314_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
    ]
