# Generated by Django 3.1.6 on 2021-03-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_auto_20210314_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetrade',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderequest',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderequest',
            name='message',
            field=models.CharField(default='message', max_length=255),
            preserve_default=False,
        ),
    ]
