# Generated by Django 3.1.7 on 2021-04-05 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_auto_20210314_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepost',
            name='payment_windows',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
