# Generated by Django 3.1.7 on 2021-04-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0011_auto_20210405_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradepost',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tradepost',
            name='payment_windows',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tradepost',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
    ]
