# Generated by Django 3.1.7 on 2021-04-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0012_auto_20210405_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetrade',
            name='rate',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderequest',
            name='rate',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
