# Generated by Django 3.1.7 on 2021-04-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0013_auto_20210409_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetrade',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Completed'), (2, 'Admin Completed'), (3, 'Owner Cancelled'), (4, 'Initiator Cancelled'), (5, 'Admin Cancelled')], default=0),
        ),
    ]
