# Generated by Django 3.1.7 on 2021-04-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0014_activetrade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Expired')], default=0),
        ),
    ]
