# Generated by Django 3.1.7 on 2021-04-09 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0015_auto_20210409_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 21, 28, 10, 339307)),
        ),
    ]
