# Generated by Django 3.1.7 on 2021-04-09 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0016_traderequest_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 15, 45, 44, 645787, tzinfo=utc)),
        ),
    ]
